---

- name: Add init script to run solr as system service
  template:
    src: init.d-solr.j2
    dest: /etc/init.d/{{ solr_service_name }}
    mode: 0744
    owner: root


- name: Install solr defaults script
  template:
    src: default-solr.in.sh.j2
    dest: /etc/default/{{ solr_service_name }}.in.sh
    mode: 0644
    owner: root