---

- name: Make solr a group exists.
  group:
    name: "{{ solr_group }}"
    state: present

- name: Make sure a solr user exists.
  user:
    name: "{{ solr_user }}"
    state: present
    group: "{{ solr_group }}"